#!/bin/sh

java -cp /Users/lorax/iesl/pdf2meta/cli/target/scala-2.9.1/pdf2meta-cli_2.9.1-0.1-SNAPSHOT.jar:/Users/lorax/iesl/bibmogrify/target/bibmogrify-assembly-0.1-SNAPSHOT.jar edu.umass.cs.iesl.bibmogrify.BibMogrify $*
